import { Product } from "./types"

const CLOUDFRONT = 'https://dn6zcp18tsbym.cloudfront.net'
const COMPRESSOR_URL = `${CLOUDFRONT}/compressor`

export const products: Product[] = [
    {
        id: '1',
        name: 'Charm 42',
        mainImageUrl: `${COMPRESSOR_URL}/Charm 42 - 01.jpg`,
        listPrice: 11000,
        salePrice: 10300,
        measurements: "L(mm) 690 W(mm) 690 H(mm) 700",
        shortDescription: "A tall, modern statement planter with a balanced square profile, perfect for showcasing feature plants at entrances, patios, and indoor spaces.",
        longDescription: "The Charm 42 flower pot is a sleek, contemporary planter designed to elevate both indoor and outdoor spaces. With its generous proportions and elegant height, this tall planter is ideal for feature plants, decorative foliage, or sculptural greenery. Its clean, symmetrical shape makes it a great choice for entryways, balconies, patios, office lobbies, and garden pathways. Whether used alone as a focal point or paired for a symmetrical look, the Charm 42 adds height, structure, and modern style to any landscape or interior design. Perfect for homeowners, landscapers, and commercial spaces looking for a durable decorative planter.",
        slug: 'charm-42',
        images: [
            `${CLOUDFRONT}/425006178_1049635029464617_6548703622942224861_n.jpeg`,
            `${CLOUDFRONT}/425160658_2132525710448331_7274797510840208439_n.jpeg`,
            `${CLOUDFRONT}/425134503_728912442310350_2876170337719638151_n.jpeg`
        ],
        category: 'flower-pots'
    },
    {
        id: '95',
        slug: '4-tier-fountain-1',
        name: '4 tier Fountain 1',
        mainImageUrl: `${COMPRESSOR_URL}/4-tier-fountain-1.jpg`,
        listPrice: 670000,
        salePrice: null,
        measurements: "L(mm) 3500 W(mm) 3500 H(mm) 2000",
        shortDescription: "A grand four-tier fountain that creates a dramatic water feature for large gardens, estates, and public spaces.",
        longDescription: "The 4 tier Fountain 1 is an impressive centrepiece designed for expansive outdoor settings, combining multiple cascading tiers with classic styling. Ideal for estates, hotels, plazas, and formal gardens, it delivers continuous movement, soothing sound, and unforgettable visual impact.",
        images: [],
        category: 'water-features'
    },
    {
        id: '58',
        slug: 'curved-pyramid',
        name: 'Curved Pyramid',
        mainImageUrl: `${COMPRESSOR_URL}/curved-pyramid.jpg`,
        listPrice: 9200,
        salePrice: null,
        measurements: "L(mm) 650 W(mm) 650 H(mm) 650",
        shortDescription: "A sculptural pyramid-shaped planter that adds architectural interest and bold lines to modern gardens.",
        longDescription: "The Curved Pyramid planter combines strong geometric form with softened edges, creating a striking focal point for contemporary landscapes. Ideal for structural planting, feature grasses, or sculptural shrubs, it works beautifully at entrances, along pathways, or as a standalone garden statement.",
        images: [],
        category: 'flower-pots'
    },

    {
        id: '73',
        slug: 'large-chateau',
        name: 'Large Chateau',
        mainImageUrl: `${COMPRESSOR_URL}/large-chateau.jpg`,
        listPrice: 7500,
        salePrice: null,
        measurements: "L(mm) 600 W(mm) 600 H(mm) 600",
        shortDescription: "A generous Chateau planter designed for larger plants and bold, traditional garden statements.",
        longDescription: "The Large Chateau planter offers ample room for substantial shrubs, small trees, and layered planting schemes. Its classic styling makes it ideal for formal gardens, grand entrances, courtyards, and terraces seeking a timeless, elegant look.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '2',
        slug: 'kivu-70',
        name: 'Kivu 70',
        mainImageUrl: `${COMPRESSOR_URL}/Kivu 70 - 01.jpg`,
        listPrice: 6100,
        salePrice: null,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 400",
        shortDescription: "A wide, low-profile planter that's perfect for shrubs, mixed arrangements, and statement greenery in gardens and outdoor living spaces.",
        longDescription: "The Kivu 70 planter offers a broad planting area with a low, contemporary silhouette that works beautifully in both residential and commercial landscapes. Its wide design makes it ideal for garden borders, patios, courtyards, and poolside landscaping, where a grounded, structured look is desired. It is perfect for creating layered plant arrangements and adding visual weight to open spaces. A practical and stylish solution for anyone seeking a large outdoor plant pot that blends modern design with generous planting capacity.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '3',
        slug: 'tanganyika-94',
        name: 'Tanganyika 94',
        mainImageUrl: `${COMPRESSOR_URL}/Tanganyika 94 - 01.jpg`,
        listPrice: 8900,
        salePrice: null,
        measurements: "L(mm) 940 W(mm) 940 H(mm) 400",
        shortDescription: "An extra-wide planter designed for bold landscaping, perfect for large plants, shrubs, or layered garden arrangements.",
        longDescription: "Make a bold landscaping statement with the Tanganyika 94 flower pot, a generously sized planter built for impactful plant displays. Its expansive design provides substantial space for large shrubs, grouped plants, or decorative garden arrangements. The low, wide profile is ideal for driveways, garden edges, commercial entrances, and expansive patios, where it can anchor a space and add balance and structure. This planter delivers both scale and style for residential and commercial landscaping.",
        images: [],
        category: 'flower-pots'
    },
    // {
    //     id: '4',
    //     slug: 'nyala-ridge-40',
    //     name: 'Nyala Ridge 40',
    //     mainImageUrl: `${COMPRESSOR_URL}/Ridged Nyala 40 - 01.jpg`,
    //     listPrice: 3000,
    //     salePrice: 2800,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [],
    //     category: 'flower-pots'
    // },
    // {
    //     id: '5',
    //     slug: 'nyala-40',
    //     name: 'Nyala 40',
    //     mainImageUrl: `${COMPRESSOR_URL}/Nyala 40 - 01.jpg`,
    //     listPrice: 2500,
    //     salePrice: null,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [],
    //     category: 'flower-pots'
    // },
    // {
    //     id: '6',
    //     slug: 'aba-ridge-37',
    //     name: 'Aba Ridge 37',
    //     mainImageUrl: `${COMPRESSOR_URL}/Aba Ridge 37 - 01.jpg`,
    //     listPrice: 4900,
    //     salePrice: null,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [],
    //     category: 'flower-pots'
    // },
    {
        id: '7',
        slug: 'mwanza-ridge-50',
        name: 'Mwanza Ridge 50',
        mainImageUrl: `${COMPRESSOR_URL}/Ridged Mwanza 50 - 01.jpg`,
        listPrice: 7700,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 50 H(mm) 650",
        shortDescription: "A tall ridged planter that adds texture and vertical interest to gardens, patios, and entryways.",
        longDescription: "The Mwanza Ridge 50 planter stands out with its textured ridged design, adding depth and character to any planting display. Its tall form makes it ideal for feature plants, palms, ornamental grasses, or flowering arrangements that benefit from added height. Perfect for doorways, patios, balconies, and indoor corners, this planter brings both structure and decorative appeal. A stylish choice for modern and classic spaces alike.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '8',
        slug: 'mwanza-50',
        name: 'Mwanza 50',
        mainImageUrl: `${COMPRESSOR_URL}/Mwanza 50 - 01.jpg`,
        listPrice: 5400,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 650",
        shortDescription: "A tall, elegant planter ideal for statement plants and stylish indoor or outdoor décor.",
        longDescription: "The Mwanza 50 flower pot combines height and clean design to create a versatile planter suited for a variety of spaces. Perfect for feature plants, small trees, and dramatic foliage, it works beautifully in home entrances, patios, terraces, office spaces, and hotel lobbies. Its simple yet refined form makes it easy to integrate into modern and minimalist décor styles.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '9',
        slug: 'victoria-64',
        name: 'Victoria 64',
        mainImageUrl: `${COMPRESSOR_URL}/Victoria 64 - 01.jpg`,
        listPrice: 3000,
        salePrice: 2800,
        measurements: "L(mm) 640 W(mm) 640 H(mm) 200",
        shortDescription: "A wide, shallow birdbath that attracts birds while adding charm and life to your garden.",
        longDescription: "The Victoria 64 birdbath is designed to bring birds closer while enhancing the beauty of your outdoor space. Its wide basin provides ample space for birds to drink and bathe, helping create a lively and natural garden environment. With its low profile, it blends seamlessly into lawns, flower beds, and landscaped gardens while adding a decorative focal point.",
        images: [],
        category: 'birdbaths-and-feeders'
    },
    {
        id: '10',
        slug: 'asmara-44',
        name: 'Asmara 44',
        mainImageUrl: `${COMPRESSOR_URL}/Asmara 44 - 01.jpg`,
        listPrice: 6100,
        salePrice: null,
        measurements: "L(mm) 440 W(mm) 440 H(mm) 460",
        shortDescription: "A compact yet tall planter perfect for smaller spaces that still need vertical plant impact.",
        longDescription: "The Asmara 44 planter is a versatile option for adding greenery to compact areas without sacrificing height. Ideal for balconies, small patios, entryways, and indoor plant styling, it suits medium-sized plants and decorative foliage. A smart solution for homeowners and designers looking for a space-saving decorative planter.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '11',
        slug: 'asmara-55',
        name: 'Asmara 55',
        mainImageUrl: `${COMPRESSOR_URL}/Asmara 55 - 01.jpg`,
        listPrice: 8400,
        salePrice: null,
        measurements: "L(mm) 550 W(mm) 550 H(mm) 580",
        shortDescription: "A tall, well-balanced planter that adds height and elegance to patios, entrances, and garden spaces.",
        longDescription: "The Asmara 55 flower pot brings vertical interest and refined style to indoor and outdoor environments. Ideal for feature plants, leafy greens, and flowering arrangements, it works beautifully in doorways, walkways, patios, and commercial entrances. A versatile planter suited for modern landscaping and classic garden designs.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '12',
        slug: 'warri-58-with-handles',
        name: 'Warri 58 with handles',
        mainImageUrl: `${COMPRESSOR_URL}/Warri 58 with Handles - 01.jpg`,
        listPrice: 8700,
        salePrice: null,
        measurements: "L(mm) 738 W(mm) 738 H(mm) 600",
        shortDescription: "A large, practical planter with built-in handles for easier positioning and stylish greenery displays.",
        longDescription: "The Warri 58 with Handles planter combines generous planting space with added functionality. Suitable for larger plants and shrubs, the integrated handles make repositioning easier. Ideal for patios, courtyards, gardens, and commercial landscapes where both style and convenience are important.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '13',
        slug: 'warri-58',
        name: 'Warri 58',
        mainImageUrl: `${COMPRESSOR_URL}/Warri 58 - 01.jpg`,
        listPrice: 7400,
        salePrice: null,
        measurements: "L(mm) 738 W(mm) 738 H(mm) 600",
        shortDescription: "A spacious, stylish planter ideal for shrubs, feature plants, and bold garden arrangements.",
        longDescription: "The Warri 58 flower pot offers a wide planting area and tall profile, making it perfect for lush shrubs and statement greenery. Ideal for home gardens, patios, office courtyards, and commercial entrances, it provides versatility in both modern and traditional settings.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '14',
        slug: 'kananga',
        name: 'Kananga',
        mainImageUrl: `${COMPRESSOR_URL}/Kananga - 01.jpg`,
        listPrice: 5600,
        salePrice: null,
        measurements: "L(mm) 450 W(mm) 450 H(mm) 650",
        shortDescription: "A decorative garden sculpture that adds artistic character and a focal point to outdoor spaces.",
        longDescription: "The Kananga sculpture is a striking decorative piece designed to enhance gardens, patios, and landscaped areas. Its sculptural form introduces texture and artistic presence, making it a perfect focal point among plants and outdoor décor.",
        images: [`${COMPRESSOR_URL}/Kananga - 02.jpg`],
        category: 'sculptures'
    },
    {
        id: '15',
        slug: 'ulu',
        name: 'Ulu',
        mainImageUrl: `${COMPRESSOR_URL}/Ulu - 01.jpg`,
        listPrice: 2300,
        salePrice: null,
        measurements: "L(mm) 300 W(mm) 300 H(mm) 300",
        shortDescription: "A compact, versatile planter perfect for small plants, herbs, and decorative indoor or outdoor use.",
        longDescription: "The Ulu flower pot is a compact and practical planter designed for smaller plants and tight spaces. Ideal for herbs, succulents, and decorative greenery, it works well on balconies, patios, and indoor shelves.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '16',
        slug: 'ridged-trough-80x40x30',
        name: 'Ridged Trough 80x40x30',
        mainImageUrl: `${COMPRESSOR_URL}/Ridged Tough 80x40x30 - 01.jpg`,
        listPrice: 9100,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 400 H(mm) 300",
        shortDescription: "A textured trough-style water feature that brings movement, sound, and modern design to outdoor spaces.",
        longDescription: "The Ridged Trough 80x40x30 water feature adds calm, movement, and visual texture to gardens and patios. Its long rectangular shape and ridged surface create a stylish focal point while enhancing the soothing effect of flowing water.",
        images: [],
        category: 'water-features'
    },
    // {
    //     id: '17',
    //     slug: 'trough-120x35x35',
    //     name: 'Trough 120x35x35',
    //     mainImageUrl: `${CLOUDFRONT}/375545246_1229893637683629_8434508144328222437_n.jpg`,
    //     listPrice: 5750,
    //     salePrice: null,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [],
    //     category: 'water-features'
    // },
    {
        id: '18',
        slug: 'cairo-50-3-ring',
        name: 'Cairo 50 3 Ring',
        mainImageUrl: `${COMPRESSOR_URL}/Cairo 50 3 Ring - 01.jpg`,
        listPrice: 6900,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 500",
        shortDescription: "A decorative planter with ring detailing that adds texture and visual interest to plant displays.",
        longDescription: "The Cairo 50 3 Ring planter features distinctive ringed detailing that adds texture and depth. Ideal for medium to large plants, it enhances patios, entrances, and landscaped gardens with decorative style and practical planting space.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '19',
        slug: 'chanzo-60-birdbath',
        name: 'Chanzo 60 Birdbath',
        mainImageUrl: `${COMPRESSOR_URL}/Chanzo 60 Birdbath - 01.jpg`,
        listPrice: 8800,
        salePrice: 8400,
        measurements: "L(mm) 600 W(mm) 600 H(mm) 880",
        shortDescription: "A tall, elegant birdbath that attracts birds while serving as a striking garden feature.",
        longDescription: "The Chanzo 60 Birdbath attracts birds while adding height and elegance to your garden. Its elevated basin provides a safe and inviting place for birds to drink and bathe, doubling as a decorative outdoor focal point.",
        images: [],
        category: 'birdbaths-and-feeders'
    },
    {
        id: '20',
        slug: 'saza-41',
        name: 'Saza 41',
        mainImageUrl: `${COMPRESSOR_URL}/Saza 41 - 01.jpg`,
        listPrice: 6000,
        salePrice: null,
        measurements: "L(mm) 410 W(mm) 410 H(mm) 580",
        shortDescription: "A tall, compact planter that brings elegance and vertical greenery to small and medium spaces.",
        longDescription: "The Saza 41 flower pot is a stylish tall planter designed to make plants stand out without taking up too much floor space. Ideal for entryways, balconies, patios, and indoor corners.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '21',
        slug: 'nyanga',
        name: 'Nyanga',
        mainImageUrl: `${COMPRESSOR_URL}/Nyanga - 01.jpg`,
        listPrice: 12000,
        salePrice: 11100,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 1200",
        shortDescription: "An extra-tall statement planter designed for large feature plants and dramatic landscape styling.",
        longDescription: "The Nyanga flower pot is a bold, extra-tall planter built to create striking vertical impact. Perfect for palms, ornamental trees, and large shrubs in hotel entrances, office buildings, patios, and spacious gardens.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '22',
        slug: 'nyanga-with-handles',
        name: 'Nyanga With Handles',
        mainImageUrl: `${COMPRESSOR_URL}/Nyanga with handles - 01.jpg`,
        listPrice: 13500,
        salePrice: 12500,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 1200",
        shortDescription: "A dramatic extra-tall planter with built-in handles for easier placement of large feature plants.",
        longDescription: "The Nyanga With Handles planter offers impressive height and planting capacity with added convenience. Ideal for large decorative plants in commercial spaces, patios, and landscaped entrances.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '23',
        slug: '1m-table',
        name: '1m Table',
        mainImageUrl: `${COMPRESSOR_URL}/1m Table.jpg`,
        listPrice: 9999,
        salePrice: null,
        measurements: "L(mm) 1000 W(mm) 1000 H(mm) 500",
        shortDescription: "A sturdy outdoor table that adds function and style to gardens, patios, and entertainment areas.",
        longDescription: "The 1m Table is a practical and stylish addition to outdoor living spaces. Perfect for drinks, décor, and garden accessories, it fits beautifully into patios, seating areas, and commercial outdoor settings.",
        images: [],
        category: 'furniture'
    },
    {
        id: '24',
        slug: 'ridged-tuni-mini',
        name: 'Ridged Tuni Mini',
        mainImageUrl: `${COMPRESSOR_URL}/Ridged Tuni mini - 01.jpg`,
        listPrice: 1300,
        salePrice: null,
        measurements: "L(mm) 190 W(mm) 190 H(mm) 320",
        shortDescription: "A small textured planter ideal for succulents, herbs, and decorative plant accents.",
        longDescription: "The Ridged Tuni Mini planter is a compact pot with stylish ridged detailing that adds texture to small plant displays. Ideal for balconies, window sills, and tabletop greenery.",
        images: [],
        category: 'flower-pots'
    },
    // {
    //     id: '25',
    //     slug: 'spheres',
    //     name: 'Spheres',
    //     mainImageUrl: `${COMPRESSOR_URL}/Spheres - 01.jpg`,
    //     listPrice: 8800,
    //     salePrice: null,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [`${COMPRESSOR_URL}/Spheres - 02.jpg`],
    //     category: 'flower-pots'
    // },
    // {
    //     id: '26',
    //     slug: 'warri-series',
    //     name: 'Warri Series',
    //     mainImageUrl: `${COMPRESSOR_URL}/Warri Series - 01.jpg`,
    //     listPrice: 8800,
    //     salePrice: 8400,
    //     measurements: "L(mm)  W(mm)  H(mm) ",
    //     shortDescription: null,
    //     longDescription: null,
    //     images: [],
    //     category: 'flower-pots'
    // },
    {
        id: '27',
        slug: 'dala-29',
        name: 'Dala 29',
        mainImageUrl: `${COMPRESSOR_URL}/Dala 29 - 01.jpg`,
        listPrice: 7700,
        salePrice: null,
        measurements: "L(mm) 550 W(mm) 550 H(mm) 700",
        shortDescription: "A tall, wide planter designed for bold greenery and structured garden styling.",
        longDescription: "The Dala 29 flower pot offers generous width and height, making it ideal for lush plants and statement foliage. Perfect for patios, garden corners, entrances, and commercial landscapes.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '28',
        slug: 'tuni-37',
        name: 'Tuni 37',
        mainImageUrl: `${COMPRESSOR_URL}/Tuni 37 - 01.jpg`,
        listPrice: 5000,
        salePrice: 4800,
        measurements: "L(mm) 370 W(mm) 370 H(mm) 710",
        shortDescription: "A slim, tall planter ideal for vertical plant styling in compact indoor and outdoor spaces.",
        longDescription: "The Tuni 37 flower pot is a tall, slender planter designed to maximize vertical greenery while using minimal floor space. Ideal for doorways, balconies, patios, and interior corners.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '29',
        slug: 'chilwa-68',
        name: 'Chilwa 68',
        mainImageUrl: `${COMPRESSOR_URL}/Chilwa 68 - 01.jpg`,
        listPrice: 8800,
        salePrice: 8400,
        measurements: "L(mm) 680 W(mm) 680 H(mm) 358",
        shortDescription: "A wide, low-profile water feature that brings a calm, modern focal point to gardens and outdoor living spaces.",
        longDescription: "The Chilwa 68 water feature introduces the soothing presence of water into your landscape with a clean, contemporary look. Perfect for courtyards, patios, and garden corners.",
        images: [`${COMPRESSOR_URL}/Chilwa 68 - 02.jpg`],
        category: 'water-features'
    },
    {
        id: '30',
        slug: 'kananga-s',
        name: 'Kananga S',
        mainImageUrl: `${COMPRESSOR_URL}/Kananga S - 01.jpg`,
        listPrice: 3900,
        salePrice: null,
        measurements: "L(mm) 350 W(mm) 350 H(mm) 400",
        shortDescription: "A compact decorative planter that adds artistic character and greenery to smaller spaces.",
        longDescription: "The Kananga S planter offers decorative appeal in a compact size. Ideal for small plants, succulents, and decorative greenery in balconies, patios, and indoor spaces.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '31',
        slug: 'kivu-50',
        name: 'Kivu 50',
        mainImageUrl: `${COMPRESSOR_URL}/kivu-50.jpg`,
        listPrice: 3800,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 300",
        shortDescription: "A low, modern planter ideal for ground-cover plants, succulents, and compact arrangements.",
        longDescription: "The Kivu 50 planter features a shallow, contemporary design that works beautifully for low-growing plants, succulents, and mixed foliage displays. Its wide, low shape makes it perfect for patios, garden beds, balconies, and indoor spaces where a clean, modern look is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '47',
        slug: '9in-sphere',
        name: '9in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/spheres.jpg`,
        listPrice: 1800,
        salePrice: null,
        measurements: "L(mm) 230 W(mm) 230 H(mm) 230",
        shortDescription: "A small decorative concrete sphere ideal for adding sculptural interest to garden beds and walkways.",
        longDescription: "The 9in Sphere is a compact decorative feature designed to bring soft, sculptural shapes into your landscape. Use it alone as an accent, grouped with other spheres, or combined with planters to add texture and visual interest to patios, pathways, and garden beds.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '48',
        slug: '14in-sphere',
        name: '14in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/spheres.jpg`,
        listPrice: 3300,
        salePrice: null,
        measurements: "L(mm) 360 W(mm) 360 H(mm) 360",
        shortDescription: "A medium decorative sphere that adds modern, sculptural charm to outdoor and indoor spaces.",
        longDescription: "The 14in Sphere is a versatile decorative element that enhances gardens, courtyards, and entrances with a clean, rounded form. Perfect as a standalone statement, in clusters of different sizes, or paired with water features and planters for a cohesive, contemporary look.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '49',
        slug: '16in-sphere',
        name: '16in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/spheres.jpg`,
        listPrice: 4100,
        salePrice: null,
        measurements: "L(mm) 400 W(mm) 400 H(mm) 400",
        shortDescription: "A generously sized decorative sphere that creates a bold focal point in gardens and outdoor settings.",
        longDescription: "The 16in Sphere offers a striking sculptural presence, ideal for anchoring corners, pathways, and landscaped beds. Use it as a single feature or combine with other sphere sizes to create layered, contemporary garden design with subtle sophistication.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '50',
        slug: '19.5in-sphere',
        name: '19.5in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/spheres.jpg`,
        listPrice: 5200,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 500",
        shortDescription: "A large decorative sphere that adds sculptural drama and structure to outdoor landscapes.",
        longDescription: "The 19.5in Sphere is a bold design feature perfect for creating visual impact in gardens, courtyards, and driveways. Its generous size and simple form complement both modern and classic landscapes, whether used alone, in pairs, or as part of a grouped display.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '51',
        slug: '24in-sphere',
        name: '24in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/spheres.jpg`,
        listPrice: 7000,
        salePrice: null,
        measurements: "L(mm) 610 W(mm) 610 H(mm) 610",
        shortDescription: "An extra-large decorative sphere that serves as a sculptural centrepiece in spacious gardens and courtyards.",
        longDescription: "The 24in Sphere is designed for maximum visual impact, offering a strong, rounded form that anchors large outdoor spaces. Ideal for feature lawns, entranceways, and landscaped terraces, it pairs beautifully with architectural planting and modern hardscaping.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '52',
        slug: '36in-sphere',
        name: '36in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/sphere.jpg`,
        listPrice: 10000,
        salePrice: null,
        measurements: "L(mm) 920 W(mm) 920 H(mm) 920",
        shortDescription: "A substantial decorative sphere that adds sculptural scale and presence to large outdoor areas.",
        longDescription: "The 36in Sphere is a commanding design element suited to expansive gardens, estates, and commercial landscapes. Its impressive size and clean shape make it ideal as a standalone focal point or as part of a dramatic sculptural grouping that complements contemporary architecture.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '53',
        slug: '1m-sphere',
        name: '1m Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/sphere.jpg`,
        listPrice: 11000,
        salePrice: null,
        measurements: "L(mm) 1000 W(mm) 1000 H(mm) 1000",
        shortDescription: "A dramatic 1m decorative sphere that creates an eye-catching statement in any landscape.",
        longDescription: "The 1m Sphere is a show-stopping garden feature designed to transform large outdoor spaces with bold, sculptural form. Perfect for driveways, formal lawns, commercial entrances, and contemporary gardens, it delivers strong visual impact while complementing modern planting schemes and hardscape designs.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '54',
        slug: '46in-sphere',
        name: '46in Sphere',
        mainImageUrl: `${COMPRESSOR_URL}/sphere.jpg`,
        listPrice: 16800,
        salePrice: null,
        measurements: "L(mm) 1160 W(mm) 1160 H(mm) 1160",
        shortDescription: "An oversized decorative sphere designed for dramatic, architectural landscape statements.",
        longDescription: "The 46in Sphere is a monumental outdoor feature that brings powerful sculptural presence to large gardens, estates, and public or commercial spaces. Its impressive scale and simple geometry make it ideal for anchoring vistas, highlighting entrances, or punctuating expansive lawns and courtyards.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '55',
        slug: 'warri-43',
        name: 'Warri 43',
        mainImageUrl: `${COMPRESSOR_URL}/warri-43-48-58.jpg`,
        listPrice: 4600,
        salePrice: null,
        measurements: "L(mm) 550 W(mm) 550 H(mm) 450",
        shortDescription: "A medium-sized planter ideal for shrubs and lush foliage in patios, gardens, and entrances.",
        longDescription: "The Warri 43 planter offers a balanced size and rounded profile that works beautifully for medium shrubs, leafy plants, and flowering arrangements. Ideal for patios, courtyards, and pathways, it brings structure and greenery to both residential and commercial spaces.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '56',
        slug: 'warri-48',
        name: 'Warri 48',
        mainImageUrl: `${COMPRESSOR_URL}/warri-43-48-58.jpg`,
        listPrice: 4900,
        salePrice: null,
        measurements: "L(mm) 610 W(mm) 610 H(mm) 500",
        shortDescription: "A generous planter with classic lines, perfect for fuller shrubs and statement plant combinations.",
        longDescription: "The Warri 48 flower pot provides ample planting space and a timeless shape that suits a wide range of planting styles. Use it to highlight entrances, frame walkways, or create focal points on patios and terraces with bold greenery or colourful blooms.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '57',
        slug: 'tuni-48',
        name: 'Tuni 48',
        mainImageUrl: `${COMPRESSOR_URL}/tuni-48.jpg`,
        listPrice: 9000,
        salePrice: null,
        measurements: "L(mm) 480 W(mm) 480 H(mm) 1000",
        shortDescription: "A tall, slender planter that brings striking vertical presence to entrances, patios, and interior spaces.",
        longDescription: "The Tuni 48 planter is designed to draw the eye upward, making it perfect for feature plants that deserve to stand out. Its slim footprint saves floor space while its height adds drama to doorways, balconies, reception areas, and garden corners.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '59',
        slug: 'karn-a-1m',
        name: 'Karn A 1m',
        mainImageUrl: `${COMPRESSOR_URL}/karn-a-1m.jpg`,
        listPrice: 10800,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 800 H(mm) 1000",
        shortDescription: "A tall, substantial planter designed for large feature plants in spacious indoor and outdoor areas.",
        longDescription: "The Karn A 1m planter offers generous height and width, making it ideal for ornamental trees, large shrubs, and lush feature plants. Perfect for grand entrances, hotel lobbies, terraces, and landscaped gardens, it brings scale and sophistication to any setting.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '60',
        slug: 'telo-c',
        name: 'Telo C',
        mainImageUrl: `${COMPRESSOR_URL}/telo-c.jpg`,
        listPrice: 10700,
        salePrice: null,
        measurements: "L(mm) 840 W(mm) 840 H(mm) 830",
        shortDescription: "A wide, deep planter perfect for generous plant groupings and bold landscape features.",
        longDescription: "The Telo C planter provides expansive planting space suited to layered arrangements, statement shrubs, and architectural greenery. Its substantial size makes it ideal for anchoring patios, courtyards, pool areas, and commercial outdoor spaces with lush, eye-catching displays.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '61',
        slug: 'bowl-1.27m-by-50cm',
        name: 'Bowl 1.27m by 50cm',
        mainImageUrl: `${COMPRESSOR_URL}/bowl.jpg`,
        listPrice: 15200,
        salePrice: null,
        measurements: "L(mm) 1270 W(mm) 1270 H(mm) 500",
        shortDescription: "An extra-wide bowl planter that creates a dramatic, low-profile focal point for large gardens and courtyards.",
        longDescription: "The Bowl 1.27m by 50cm planter offers a generous surface area for creative planting, from sculptural succulents to lush mixed arrangements. Its broad, shallow form is ideal for courtyards, pool surrounds, commercial entrances, and open garden spaces where a strong horizontal feature is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '62',
        slug: 'nyanga-80-h',
        name: 'Nyanga 80 H',
        mainImageUrl: `${COMPRESSOR_URL}/nyanga-80-h.jpg`,
        listPrice: 6400,
        salePrice: null,
        measurements: "L(mm) 472 W(mm) 472 H(mm) 800",
        shortDescription: "A tall, slim planter that brings vertical greenery to compact spaces indoors and out.",
        longDescription: "The Nyanga 80 H planter combines a narrow footprint with impressive height, making it perfect for hallways, balconies, entrances, and patio corners. Ideal for feature grasses, palms, and upright foliage, it delivers height and elegance without overwhelming smaller areas.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '63',
        slug: '2-tier-fountain',
        name: '2 Tier Fountain',
        mainImageUrl: `${COMPRESSOR_URL}/2-tier-fountain.jpg`,
        listPrice: 14900,
        salePrice: null,
        measurements: "L(mm) 1100 W(mm) 1100 H(mm) 1400",
        shortDescription: "A classic two-tier fountain that brings soothing sound, movement, and old-world charm to gardens and courtyards.",
        longDescription: "The 2 Tier Fountain is a timeless water feature designed to enhance outdoor spaces with gentle cascading water and elegant styling. Ideal for courtyards, formal gardens, and entrances, it creates a relaxing focal point that attracts attention and elevates the overall ambience.",
        images: [],
        category: 'water-features'
    },
    {
        id: '64',
        slug: 'hourglass-45.5d-by-100h',
        name: 'Hourglass 45.5D by 100H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 8300,
        salePrice: null,
        measurements: "L(mm) 455 W(mm) 455 H(mm) 1000",
        shortDescription: "A tall hourglass-shaped planter that adds sculptural elegance and height to modern plant displays.",
        longDescription: "The Hourglass 45.5D by 100H planter features a graceful curved profile that draws the eye and complements contemporary architecture. Perfect for entrances, patios, balconies, and indoor spaces, it pairs beautifully with upright plants and cascading foliage for dramatic visual effect.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '65',
        slug: 'hourglass-22.8d-by-50h',
        name: 'Hourglass 22.8D by 50H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 3600,
        salePrice: null,
        measurements: "L(mm) 228 W(mm) 228 H(mm) 500",
        shortDescription: "A compact hourglass planter ideal for tabletops, steps, and smaller corners that need a decorative touch.",
        longDescription: "The Hourglass 22.8D by 50H planter offers the same elegant curves as the larger hourglass range in a smaller, space-saving size. Perfect for herbs, succulents, and decorative plants, it suits balconies, porch steps, window areas, and interior styling.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '66',
        slug: 'hourglass-32d-by-70h',
        name: 'Hourglass 32D by 70H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 5600,
        salePrice: null,
        measurements: "L(mm) 320 W(mm) 320 H(mm) 700",
        shortDescription: "A medium-sized hourglass planter that blends sculptural form with practical planting depth.",
        longDescription: "The Hourglass 32D by 70H planter is ideal for medium-sized plants that benefit from added height and a decorative silhouette. Its balanced proportions make it suitable for entrances, patios, terraces, and interior spaces that call for a refined statement piece.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '67',
        slug: 'hourglass-42d-by-60h',
        name: 'Hourglass 42D by 60H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 5700,
        salePrice: null,
        measurements: "L(mm) 420 W(mm) 420 H(mm) 600",
        shortDescription: "A wide hourglass planter that offers both sculptural style and room for fuller plantings.",
        longDescription: "The Hourglass 42D by 60H planter provides generous planting space while retaining the elegant hourglass silhouette. Ideal for lush foliage, flowering plants, and mixed arrangements, it enhances patios, entrances, and garden features with a refined, modern look.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '68',
        slug: 'hourglass-26d-by-37.5h',
        name: 'Hourglass 26D by 37.5H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 3500,
        salePrice: null,
        measurements: "L(mm) 260 W(mm) 260 H(mm) 375",
        shortDescription: "A small hourglass planter perfect for accent planting on walls, steps, and compact balconies.",
        longDescription: "The Hourglass 26D by 37.5H planter delivers a stylish curved profile in a petite size, ideal for herbs, trailing plants, and decorative greenery. It works well in tight spaces, on ledges, or as part of a grouped display with other hourglass planters.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '69',
        slug: 'hourglass-60d-by-100h',
        name: 'Hourglass 60D by 100H',
        mainImageUrl: `${COMPRESSOR_URL}/hourglass.jpg`,
        listPrice: 9800,
        salePrice: null,
        measurements: "L(mm) 600 W(mm) 600 H(mm) 1000",
        shortDescription: "An impressive tall hourglass planter designed for major feature plants and bold entrances.",
        longDescription: "The Hourglass 60D by 100H planter combines dramatic height with a sculptural silhouette, making it ideal for statement trees, palms, and large shrubs. Perfect for grand entrances, hotel foyers, terraces, and landscaped gardens that call for a standout piece.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '70',
        slug: 'shikie-plain-vase',
        name: 'Shikie Plain Vase',
        mainImageUrl: `${COMPRESSOR_URL}/shikie-plain-vase.jpg`,
        listPrice: 3600,
        salePrice: null,
        measurements: "L(mm) 350 W(mm) 350 H(mm) 430",
        shortDescription: "A classic vase-style planter that adds soft curves and timeless appeal to plant displays.",
        longDescription: "The Shikie Plain Vase offers a simple, elegant shape that suits a wide variety of plants and décor styles. Ideal for indoor corners, patios, verandas, and garden settings, it blends seamlessly into both modern and traditional spaces while showcasing your favourite greenery.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '71',
        slug: 'shikie-h-vase',
        name: 'Shikie H Vase',
        mainImageUrl: `${COMPRESSOR_URL}/shikie-h-vase.jpg`,
        listPrice: 4300,
        salePrice: null,
        measurements: "L(mm) 350 W(mm) 350 H(mm) 430",
        shortDescription: "A decorative vase-style planter with added detailing that enhances classic and rustic plant styling.",
        longDescription: "The Shikie H Vase brings subtle character and charm to your plant displays, making it ideal for flowering plants, trailing foliage, and decorative arrangements. Perfect for verandas, patios, interior styling, and garden features where a touch of detail is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '72',
        slug: 'medium-chateau',
        name: 'Medium Chateau',
        mainImageUrl: `${COMPRESSOR_URL}/medium-chateau.jpg`,
        listPrice: 4100,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 430",
        shortDescription: "A decorative planter with classic Chateau styling, ideal for traditional gardens and elegant entrances.",
        longDescription: "The Medium Chateau planter combines refined detailing with a practical planting area, making it perfect for shrubs, flowers, and decorative greenery. Use it to frame doorways, line pathways, or accent patios where a touch of classical charm is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '74',
        slug: 'chateau-xl',
        name: 'Chateau XL',
        mainImageUrl: `${COMPRESSOR_URL}/chateau-xl.jpg`,
        listPrice: 12500,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 800 H(mm) 1000",
        shortDescription: "An extra-large Chateau planter that delivers impressive scale and traditional elegance for major garden features.",
        longDescription: "The Chateau XL planter is built for impact, with substantial proportions suited to large shrubs, ornamental trees, and grand planting schemes. Ideal for estates, hotels, entrances, and formal landscapes, it becomes a centrepiece wherever it is placed.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '75',
        slug: 'chateau-xl-b',
        name: 'Chateau XL B',
        mainImageUrl: `${COMPRESSOR_URL}/chateau-xl-b.jpg`,
        listPrice: 14500,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 800 H(mm) 1000",
        shortDescription: "A bold Chateau planter variation that adds grandeur and presence to classic and contemporary landscapes alike.",
        longDescription: "The Chateau XL B planter offers the same impressive scale as the Chateau XL with a distinctive styling variation, ideal for large feature plantings. Use it to anchor formal entrances, long driveways, terraces, and high-impact garden designs.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '76',
        slug: 'elsie-amph',
        name: 'Elsie Amph',
        mainImageUrl: `${COMPRESSOR_URL}/elsie-amph.jpg`,
        listPrice: 3600,
        salePrice: null,
        measurements: "L(mm) 317 W(mm) 317 H(mm) 365",
        shortDescription: "A classic amphora-style planter that adds rustic charm and soft curves to plant displays.",
        longDescription: "The Elsie Amph planter is inspired by traditional amphora shapes, making it perfect for flowering plants, trailing greenery, and decorative arrangements. Ideal for patios, verandas, courtyards, and interior styling where a warm, timeless look is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '77',
        slug: 'elsie-amph-4-handles',
        name: 'Elsie Amph 4 Handles',
        mainImageUrl: `${COMPRESSOR_URL}/elsie-amph-4-handles.jpg`,
        listPrice: 5000,
        salePrice: null,
        measurements: "L(mm) 317 W(mm) 317 H(mm) 365",
        shortDescription: "An amphora-style planter with four handles that delivers extra character and decorative detail.",
        longDescription: "The Elsie Amph 4 Handles planter adds a charming, handcrafted feel to gardens and interiors with its multiple handle design. Perfect for statement plants, flowering displays, and rustic styling, it suits patios, covered terraces, and indoor feature corners.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '78',
        slug: 'meeta-lantern',
        name: 'Meeta Lantern',
        mainImageUrl: `${COMPRESSOR_URL}/meeta-lantern.jpg`,
        listPrice: 7500,
        salePrice: null,
        measurements: "L(mm) 545 W(mm) 545 H(mm) 600",
        shortDescription: "A decorative lantern-style feature that adds ambience and sculptural interest to patios and garden spaces.",
        longDescription: "The Meeta Lantern is a versatile décor piece designed to complement outdoor seating areas, pathways, and landscaped corners. Use it as a sculptural accent by day and pair it with lighting for warm, atmospheric evenings in your garden or entertainment area.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '79',
        slug: 'large-hemisphere',
        name: 'Large Hemisphere',
        mainImageUrl: `${COMPRESSOR_URL}/large-hemisphere.jpg`,
        listPrice: 7000,
        salePrice: null,
        measurements: "L(mm) 880 W(mm) 880 H(mm) 450",
        shortDescription: "A large hemisphere planter or feature bowl that creates a soft, modern focal point in gardens and courtyards.",
        longDescription: "The Large Hemisphere can be used as a generous planter or as a sculptural bowl-style feature in contemporary landscapes. Its curved, open form is ideal for creative planting, decorative stone arrangements, or as a standalone design element in patios and garden beds.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '80',
        slug: 'amphora-s',
        name: 'Amphora S',
        mainImageUrl: `${COMPRESSOR_URL}/amphora-s.jpg`,
        listPrice: 3600,
        salePrice: null,
        measurements: "L(mm) 520 W(mm) 520 H(mm) 430",
        shortDescription: "A smaller amphora-inspired planter that brings classic curves and charm to compact spaces.",
        longDescription: "The Amphora S planter is designed for those who love traditional amphora styling in a more compact format. Ideal for patios, balconies, verandas, and indoor styling, it suits flowering plants, trailing foliage, and decorative arrangements that need a touch of old-world character.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '81',
        slug: 'planter-1.9x45x45',
        name: 'Planter 1.9x45x45',
        mainImageUrl: `${COMPRESSOR_URL}/planter-1.9x45x45.jpg`,
        listPrice: 16500,
        salePrice: null,
        measurements: "L(mm) 1900 W(mm) 450 H(mm) 450",
        shortDescription: "A long rectangular planter ideal for creating low hedges, borders, and screening with greenery.",
        longDescription: "The Planter 1.9x45x45 is perfect for lining pathways, defining outdoor rooms, and adding structured planting along walls or edges. Its extended length makes it ideal for grasses, shrubs, and repeated plantings that create a clean, contemporary boundary in gardens and courtyards.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '82',
        slug: 'planter-0.8x45x45',
        name: 'Planter 0.8x45x45',
        mainImageUrl: `${COMPRESSOR_URL}/planter-0.8x45x45.jpg`,
        listPrice: 6900,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 450 H(mm) 450",
        shortDescription: "A versatile rectangular planter suited to patios, balconies, and garden edging.",
        longDescription: "The Planter 0.8x45x45 offers a practical size for creating neat borders, defining seating areas, and adding structure to smaller spaces. Ideal for shrubs, grasses, and seasonal colour, it works well in both residential and commercial landscapes.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '83',
        slug: 'planter-0.8x30x45',
        name: 'Planter 0.8x30x45',
        mainImageUrl: `${COMPRESSOR_URL}/planter-0.8x45x45.jpg`,
        listPrice: 6200,
        salePrice: null,
        measurements: "L(mm) 800 W(mm) 300 H(mm) 450",
        shortDescription: "A slimmer rectangular planter perfect for narrow spaces, ledges, and balcony edges.",
        longDescription: "The Planter 0.8x30x45 is designed for tighter spots where full-width planters won't fit, while still offering enough depth for healthy root growth. Ideal for herbs, flowers, and low hedging plants along balconies, walls, and walkways.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '84',
        slug: 'rc-planter-100x30x60',
        name: 'RC Planter - 100x30x60',
        mainImageUrl: `${COMPRESSOR_URL}/rc-planter-100x30x60.jpg`,
        listPrice: 8900,
        salePrice: null,
        measurements: "L(mm) 1000 W(mm) 300 H(mm) 600",
        shortDescription: "A tall, narrow rectangular planter ideal for privacy planting and space-efficient screening.",
        longDescription: "The RC Planter - 100x30x60 is perfect for creating living screens with grasses, bamboo, or upright shrubs in compact areas. Its slim footprint and good height make it well suited to balconies, along fences, and beside seating areas where greenery and privacy are both priorities.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '85',
        slug: 'bela-60',
        name: 'Bela 60',
        mainImageUrl: `${COMPRESSOR_URL}/bela-60.jpg`,
        listPrice: 4700,
        salePrice: null,
        measurements: "L(mm) 525 W(mm) 525 H(mm) 600",
        shortDescription: "A mid-sized planter with clean lines, ideal for feature shrubs and leafy plants.",
        longDescription: "The Bela 60 planter delivers a balanced size and simple, modern look that fits effortlessly into patios, entrances, and garden beds. It’s perfect for showcasing statement shrubs, flowering plants, and lush greenery in both residential and commercial spaces.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '86',
        slug: 'bela-80',
        name: 'Bela 80',
        mainImageUrl: `${COMPRESSOR_URL}/bela-80.jpg`,
        listPrice: 7000,
        salePrice: null,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 800",
        shortDescription: "A large, modern planter designed for generous planting and bold outdoor statements.",
        longDescription: "The Bela 80 planter offers impressive capacity for larger shrubs, small trees, and layered planting combinations. Ideal for framing entrances, anchoring patios, and enhancing commercial landscapes, it brings structure and style to any setting.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '87',
        slug: 'bela-100',
        name: 'Bela 100',
        mainImageUrl: `${COMPRESSOR_URL}/bela-100.jpg`,
        listPrice: 11200,
        salePrice: null,
        measurements: "L(mm) 880 W(mm) 880 H(mm) 1000",
        shortDescription: "An extra-large planter built for substantial feature plants and dramatic landscape impact.",
        longDescription: "The Bela 100 planter is ideal for sizeable ornamental trees, lush shrubs, and statement planting schemes in expansive spaces. Perfect for estates, hotels, office complexes, and large patios, it delivers both scale and contemporary style.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '88',
        slug: 'rishi-a',
        name: 'Rishi A',
        mainImageUrl: `${COMPRESSOR_URL}/rishi-a.jpg`,
        listPrice: 4800,
        salePrice: null,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 230",
        shortDescription: "A shallow, wide planter ideal for low-growing plants, succulents, and layered ground-cover displays.",
        longDescription: "The Rishi A planter offers a broad, low profile that is perfect for creative arrangements with succulents, grasses, and compact flowering plants. Ideal for patios, terraces, and garden beds where a subtle yet stylish feature is desired.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '89',
        slug: 'ridged-tuni-45',
        name: 'Ridged Tuni 45',
        mainImageUrl: `${COMPRESSOR_URL}/ridged-tuni-45.jpg`,
        listPrice: 10000,
        salePrice: null,
        measurements: "L(mm) 450 W(mm) 450 H(mm) 900",
        shortDescription: "A tall ridged planter that combines texture and height for striking plant displays.",
        longDescription: "The Ridged Tuni 45 planter stands out with its vertical ridged design and generous height, making it ideal for feature plants, tall grasses, and architectural foliage. Perfect for entrances, patios, and interior statement corners, it adds both texture and elegance to your space.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '90',
        slug: '1m-table-with-sphere-legs',
        name: '1m table with sphere legs',
        mainImageUrl: `${COMPRESSOR_URL}/1m-table-with-sphere-legs.jpg`,
        listPrice: 12000,
        salePrice: null,
        measurements: "L(mm) 1000 W(mm) 1000 H(mm) 400",
        shortDescription: "A 1m decorative table with sculptural sphere legs that adds character to patios and entertainment areas.",
        longDescription: "The 1m table with sphere legs is a functional décor piece that doubles as a sculptural feature in outdoor living spaces. Ideal for drinks, décor, and gatherings on patios, pool decks, and terraces, it pairs beautifully with modern garden furniture and contemporary landscaping.",
        images: [],
        category: 'sculptures'
    },
    {
        id: '91',
        slug: 'ridged-asmara-44',
        name: 'Ridged Asmara 44',
        mainImageUrl: `${COMPRESSOR_URL}/ridged-asmara-44.jpg`,
        listPrice: 7200,
        salePrice: null,
        measurements: "L(mm) 630 W(mm) 630 H(mm) 580",
        shortDescription: "A textured planter with a ridged finish that adds depth and interest to plant arrangements.",
        longDescription: "The Ridged Asmara 44 planter combines practical planting capacity with a distinctive ridged surface that catches light and shadow. Ideal for patios, entrances, and garden beds, it suits a wide range of shrubs and foliage while adding subtle decorative detail.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '92',
        slug: 'pambo-pyramid',
        name: 'Pambo Pyramid',
        mainImageUrl: `${COMPRESSOR_URL}/pambo-pyramid.jpg`,
        listPrice: 31800,
        salePrice: null,
        measurements: "L(mm) 1050 W(mm) 1050 H(mm) 1000",
        shortDescription: "A large pyramid-shaped planter that creates a bold architectural statement in contemporary landscapes.",
        longDescription: "The Pambo Pyramid planter is designed for dramatic impact, combining a strong geometric form with generous planting volume. Ideal for feature trees, structural shrubs, and high-impact arrangements, it suits modern gardens, commercial properties, and grand entrances where design presence matters.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '93',
        slug: 'large-birdbath',
        name: 'Large Birdbath',
        mainImageUrl: `${COMPRESSOR_URL}/large-birdbath.jpg`,
        listPrice: 8400,
        salePrice: null,
        measurements: "L(mm) 1050 W(mm) 1050 H(mm) 950",
        shortDescription: "A generously sized birdbath that attracts wildlife while serving as a striking garden centrepiece.",
        longDescription: "The Large Birdbath offers a wide basin and elevated profile that invite birds to drink and bathe, bringing life and movement to your garden. Ideal for lawns, flower beds, and courtyards, it also acts as a sculptural focal point in both traditional and contemporary landscapes.",
        images: [],
        category: 'water-features'
    },
    {
        id: '94',
        slug: 'chateau-m-with-pedestal',
        name: 'Chateau M with Pedestal',
        mainImageUrl: `${COMPRESSOR_URL}/chateau-m-with-pedestal.jpg`,
        listPrice: 13100,
        salePrice: null,
        measurements: "L(mm) 500 W(mm) 500 H(mm) 500",
        shortDescription: "A Chateau-style planter set on a pedestal, perfect for elevating feature plants in classic gardens.",
        longDescription: "The Chateau M with Pedestal combines a decorative planter with an integrated base to raise plants for extra impact. Ideal for framing entrances, lining pathways, and highlighting focal points, it suits formal gardens, verandas, and elegant outdoor entertaining areas.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '96',
        slug: 'cylinder-750d-by-400h',
        name: 'Cylinder 750D by 400H',
        mainImageUrl: `${COMPRESSOR_URL}/cylinder-750d-by-400h.jpg`,
        listPrice: 6700,
        salePrice: null,
        measurements: "L(mm) 750 W(mm) 750 H(mm) 400",
        shortDescription: "A wide cylindrical planter ideal for low, full plantings in contemporary garden designs.",
        longDescription: "The Cylinder 750D by 400H planter offers a generous round footprint with a modest height, making it perfect for full, layered plantings and low-profile displays. Ideal for patios, courtyards, and commercial spaces, it complements modern architecture and structured planting schemes.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '97',
        slug: 'winnie-large',
        name: 'Winnie Large',
        mainImageUrl: `${COMPRESSOR_URL}/winnie-large.jpg`,
        listPrice: 6700,
        salePrice: null,
        measurements: "L(mm) 580 W(mm) 580 H(mm) 700",
        shortDescription: "A large, versatile planter with soft curves suitable for generous shrubs and lush planting.",
        longDescription: "The Winnie Large planter combines a substantial planting area with a gentle curved profile that suits both modern and traditional gardens. Ideal for patios, entrances, and garden beds, it is perfect for feature shrubs, flowering plants, and layered greenery.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '98',
        slug: '700d-bowl-with-stand',
        name: '700D Bowl with stand',
        mainImageUrl: `${COMPRESSOR_URL}/500d-bowl-with-stand.jpg`,
        listPrice: 6000,
        salePrice: null,
        measurements: "L(mm) 700 W(mm) 700 H(mm) 450",
        shortDescription: "A raised bowl planter on a stand that adds height and elegance to plant or decorative displays.",
        longDescription: "The 700D Bowl with stand lifts planting or decorative arrangements for greater visibility and impact. Ideal for patios, entrances, and garden focal points, it can be used for flowers, succulents, or decorative stones to create a stylish raised feature.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '99',
        slug: 'winnie-medium',
        name: 'Winnie Medium',
        mainImageUrl: `${COMPRESSOR_URL}/winnie-medium.jpg`,
        listPrice: 5700,
        salePrice: null,
        measurements: "L(mm) 580 W(mm) 580 H(mm) 545",
        shortDescription: "A medium-sized curved planter ideal for versatile planting in patios, gardens, and courtyards.",
        longDescription: "The Winnie Medium planter offers a practical size and soft shape that works well with a wide range of plants, from shrubs and grasses to flowering displays. Its adaptable design makes it an easy fit for residential gardens, balconies, and commercial outdoor areas.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '100',
        slug: 'kivu-40-30',
        name: 'Kivu 40 (30)',
        mainImageUrl: `${COMPRESSOR_URL}/kivu-40-30.jpg`,
        listPrice: 2700,
        salePrice: null,
        measurements: "L(mm) 400 W(mm) 400 H(mm) 300",
        shortDescription: "A compact, low-profile planter ideal for smaller plants, herbs, and succulents.",
        longDescription: "The Kivu 40 (30) planter is a space-efficient option for balconies, window areas, patios, and indoor styling. Its shallow, square design works well for herbs, small flowering plants, and decorative succulents while maintaining a clean, modern look.",
        images: [],
        category: 'flower-pots'
    },
    {
        id: '101',
        slug: 'luna',
        name: 'Luna',
        mainImageUrl: `${COMPRESSOR_URL}/luna.jpg`,
        listPrice: 6500,
        salePrice: null,
        measurements: "L(mm) 450 W(mm) 450 H(mm) 750",
        shortDescription: "A tall, elegant planter with a soft rounded profile that suits modern indoor and outdoor spaces.",
        longDescription: "The Luna planter brings height and smooth, contemporary curves to plant styling, making it ideal for feature plants in entrances, living areas, patios, and balconies. Its refined shape pairs well with both leafy greens and flowering arrangements for a polished, modern look.",
        images: [],
        category: 'flower-pots'
    }
]
